services:
  backend:
    build:
      context: ./springbootbackend
      dockerfile: backend.Dockerfile
    container_name: task-backend
    ports:
      - "2090:2090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:projectdb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
    networks:
      - task-network

  frontend:
    build:
      context: ./reactfrontend
      dockerfile: frontend.Dockerfile
    container_name: task-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
